server:
  port: 8080
  forward-headers-strategy: framework

spring:
  application:
    name: property
  datasource:
    url: jdbc:postgresql://postgres:5432/property_db
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://registry:8761/eureka/}
  instance:
    prefer-ip-address: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    use-root-path: true

management:
  endpoints:
    web:
      exposure:
        include: health,info